export const GET_ITEMS = 'GET_ITEMS';
export const GET_EDUCATION_ITEMS = 'GET_EDUCATION_ITEMS';
export const GET_WORK_EXPERIENCE_ITEMS = 'GET_WORK_EXPERIENCE_ITEMS';
export const GET_VOLUNTEER_EXPERIENCE_ITEMS = 'GET_VOLUNTEER_EXPERIENCE_ITEMS';

