# Generated by Django 3.0.7 on 2020-06-08 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='section',
            field=models.CharField(choices=[('education', 'Education'), ('project', 'Project'), ('work-experience', 'Work Experience'), ('volunteer-experience', 'Volunteer Experience')], default='work-experience', max_length=255),
            preserve_default=False,
        ),
    ]
