# Generated by Django 3.0.7 on 2020-06-08 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_item_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='class_year',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
